### ISSUE TITLE
 Build error on Windows

### ISSUE THREAD

**Issue by AselSiriwardena** [cfallin/rust-oping#12]
Compiling oping v0.3.4
error: failed to run custom build command for `oping v0.3.4`

Caused by:
  process didn't exit successfully: `C:\Users\User\Desktop\abcd\target\debug\build\oping-8e0817e189ebe78f\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\oping-0.3.4\build.rs:6:5
stack backtrace:
   0: core::fmt::write
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\fmt\mod.rs:1052
   1: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\io\mod.rs:1426
   2: std::sys_common::backtrace::_print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:62
   3: std::sys_common::backtrace::print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:49
   4: std::panicking::default_hook::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:204
   5: std::panicking::default_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:224
   6: std::panicking::rust_panic_with_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:472
   7: std::panicking::begin_panic_handler
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:380
   8: core::panicking::panic_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\panicking.rs:85
   9: core::option::expect_none_failed
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\option.rs:1199
  10: core::result::Result<std::process::ExitStatus, std::io::error::Error>::unwrap<std::process::ExitStatus,std::io::error::Error>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\result.rs:963
  11: build_script_build::main
             at .\build.rs:6
  12: std::rt::lang_start::{{closure}}<()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\rt.rs:67
  13: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

Process finished with exit code 101

**Comment by cfallin** [comment]
Yes, you're getting a "file not found" when trying to invoke `sh autogen.sh`. Three questions:

- Do you have the liboping submodule checked out? (`git submodule update --init` if the `liboping` directory is empty)
- Do you have a Unix-like environment with `sh`, `autogen`, `autoconf`, make and gcc, etc.? MinGW might work -- I've never tried, though.
- Finally, I don't actually know if liboping (for which this Rust crate is just a wrapper) supports WIndows. I would try debugging the issue by building liboping itself first, and making sure its included `oping` demo program works. If there are any issues, the oping project is on GitHub too at [octo/liboping](https://github.com/octo/liboping).

(EDIT: three questions, not two. I can't count today.)

**Comment by AselSiriwardena** [comment]
- I have tried this command - `git submodule update --init`

- Is this library only works on Unix-like environment s? 

- I have tried to run demo but its also the same.
