### ISSUE TITLE
Example fails to build on MacOS

### ISSUE THREAD

**Issue by j4loop** [cfallin/rust-oping#14]
Hello I was trying to test out the example provided running on Mac (works on Linux) and received the following error when running 'cargo build':

config.status: executing libtool commands

--- stderr
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:57: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:57: You should run autoupdate.
../../lib/autoconf/general.m4:207: AC_HELP_STRING is expanded from...
configure.ac:57: the top level
configure.ac:57: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:57: You should run autoupdate.
../../lib/autoconf/general.m4:207: AC_HELP_STRING is expanded from...
configure.ac:57: the top level
configure.ac:36: installing './compile'
configure.ac:50: installing './config.guess'
configure.ac:50: installing './config.sub'
configure.ac:12: installing './install-sh'
configure.ac:12: installing './missing'
Makefile.am: installing './INSTALL'
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/oping-0.3.5/build.rs:34:5

I am able to go into the liboping directory (oping-0.3.5) and run the "configure, make and make install" to build oping manually. 

TEST-BOX:test_ping marco$ uname -a
Darwin TEST-BOX 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

I tried changing some things in the build.rs file but havent had much luck.

Any ideas?

**Comment by j4loop** [comment]
If I comment out the configure's whole command setting (and run configure and make manually) OR set the entire path to the configure script it will build

fn build_and_statically_link() {
    Command::new("sh")
        .current_dir("liboping/")
        .arg("autogen.sh")
        .status()
        .unwrap();


    Command::new("/Users/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/oping-0.3.5/liboping/configure")
    //Command::new("./configure")
        .current_dir("liboping/")
        .arg("--with-perl-bindings=no")
        .status()
        .unwrap();

    cc::Build::new()
        .define("HAVE_CONFIG_H", None)
        .file("liboping/src/liboping.c")
        .include("liboping/src/")
        .compile("liboping.a");
}

TEST-BOX:liboping marco$ cargo build
   Compiling oping v0.3.5 (/Users/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/oping-0.3.5)
warning: liboping/src/liboping.c:743:19: warning: comparison of integers of different signs: 'unsigned long' and 'int' [-Wsign-compare]
warning:         if (sizeof (buf) < buflen)
warning:             ~~~~~~~~~~~~ ^ ~~~~~~
warning: 1 warning generated.
    Finished dev [unoptimized + debuginfo] target(s) in 26.03s

**Comment by cfallin** [comment]
I have no idea, sorry; I don't have a Mac, so I'm not able to debug or support that platform.

I suspect from the error messages that it may have something to do with the version of `autoconf` installed, but that's just a guess.

Honestly, the vast majority of issues opened on this project have to do with failures to build the bundled liboping automatically, and it's not even my library; I'm starting to get quite frustrated (it's not you, don't worry) and thinking that the best use of my time is simply to remove the bundled copy, and require it to be pre-installed on the system. I think I'll go ahead and do that (and semver-bump so it doesn't break anyone).

**Comment by cfallin** [comment]
Closed with version 0.4.0, just released on crates.io.
