### ISSUE TITLE
build fails on liboping

### ISSUE THREAD

**Issue by sjbeskur** [cfallin/rust-oping#4]
I've installed the liboping library, however, rust-oping fails to build as it cannot seem to locate it.  Is there an additional step that I'm missing?  

```
  = note: /usr/bin/ld: cannot find -loping
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `oping`.
```

**Comment by sjbeskur** [comment]
solved:
sudo ln -s /opt/oping/lib/liboping.so.0 /usr/local/lib/liboping.so

then 

sudo ldconfig -v

**Comment by cfallin** [comment]
Glad you worked out the issue! However this has made me realize that requiring `liboping` to be installed separately is a bit of a pain, so I've updated the crate to include `liboping` automatically (bundled in its tree and built into the crate binary).

If you use v0.3.2 or above, you should be able to just depend on the crate without the work above.

Good luck and let me know if any issues!
