### ISSUE TITLE
PING_OPT_DEVICE

### ISSUE THREAD

**Issue by robbym** [cfallin/rust-oping#6]
I need to specify the device I want to use. For example, with ping6 I do:
`ping6 -I wpan0 ff02::1`

I believe liboping allows this via `ping_setopt (*obj, PING_OPT_DEVICE, "wpan0");`

**Comment by cfallin** [comment]
A PR for this would be welcome if you'd like to contribute it!

**Comment by robbym** [comment]
Sure thing!
